export const ADD_POINT = 'ADD_POINT';
export const REORDER_POINTS = 'REORDER_POINTS';
export const REMOVE_POINT = 'REMOVE_POINT';
export const UPDATE_POINT = 'UPDATE_POINT';
export const SET_CENTER_MAP = 'SET_CENTER_MAP';
export const MAP_LOAD_SUCCESS = 'MAP_LOAD_SUCCESS';
